"""test table delete

Revision ID: 650c2ed14deb
Revises: 
Create Date: 2023-04-15 09:35:48.542271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650c2ed14deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ss', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ss')
    # ### end Alembic commands ###
